config/routes.rb
Rails.application.routes.draw do
  resources :archives
  devise_for :users
  resources :publications
  resources :doubts
  resources :institutes
  resources :comentaries
  resources :questions

  root :to => "website#home"
  get "home" => "website#home", as: :home  
  get "about" => "website#about", as: :about
  get "game" => "website#game", as: :game
  get "vagas" => "website#vagas", as: :vagas
  get "videos" => "website#videos", as: :videos
  get "compromisso_e_atitude" => "website#compromisso_e_atitude", as: :compromisso_e_atitude
  get "ministerio_publico" => "website#ministerio_publico", as: :ministerio_publico


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
	    
	    if user
	    	if user.access_level.level == 1 # 4: Perfil nível Administrador
	    		can :manage, :all
	    	elsif user.access_level.level == 2 # 2: Perfil nível Editor
	    		can :dashboard
	    		can :access, :rails_admin	    		
	    		can :manage, Archive
	    		can :manage, Doubt
	    		can :manage, Institute
	    		can :manage, Question			
			elsif user.access_level.level == 3 # 3: Perfil nível Publicador
				can :access, :rails_admin
				can :dashboard
				can :manage, Publication
				can :manage, Comentary
			elsif user.access_level.level == 4 # 4: Perfil nível Policial
				can :access, :rails_admin
				can :dashboard				
				can :manage, OccurrenceBulletin
				can :manage, AnonymousDenounciation
				can :manage, Person
				can :manage, Phone
				can :manage, Address
			end	
	    end

	end
end

app/models/access_level.rb
class AccessLevel < ApplicationRecord
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :category
  has_attached_file :arch
  validates :arch, :attachment_content_type => { :content_type => ['application/pdf', 'video/mp4'] }
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comentary.rb
class Comentary < ApplicationRecord
  belongs_to :publication
end

app/models/doubt.rb
class Doubt < ApplicationRecord
  belongs_to :question
end

app/models/institute.rb
class Institute < ApplicationRecord
  belongs_to :phone
  belongs_to :address
end

app/models/news.rb
class News < ApplicationRecord

end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :phone
  belongs_to :address
end

app/models/phone.rb
class Phone < ApplicationRecord
end

app/models/publication.rb
class Publication < ApplicationRecord
	has_many :comentaries
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
include RailsAdminCharts

class User < ApplicationRecord 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :access_level
  belongs_to :person
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    # @publications = Publication.all
    @publications = Publication.page(params[:page]).per(2)
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :date, :content)
    end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/doubts_helper.rb
module DoubtsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<!DOCTYPE html>
<html lang="pt-BR">

	<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Igor Felipe Boniatti">
    <meta name="description" content="Protótipo de website para auxiliar vítimas de violência doméstica e familiar no município de Chapecó.">

    <%= content_for :title, "Publicações - Projeto Maria da Penha Chapecó" %>    
    <%= favicon_link_tag 'logo_fundo_preto.png' %>

    <%= stylesheet_link_tag 'bootstrap/bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'home/index', media: 'all', 'data-turbolinks-track' => true %>
	</head>

	<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="<%= home_path %>">
          <%= link_to(image_tag("logo_fundo_preto.png", :alt => "logo", :title => "Home"), home_path ) %>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="http://www.planalto.gov.br/ccivil_03/_Ato2004-2006/2006/Lei/L11340.htm" target="_blank">A LEI MARIA DA PENHA</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="<%= doubts_path %>">TIRA-DÚVIDAS</a>
            </li>
            <li class="nav-item dropdown active">
              <a class="nav-link js-scroll-trigger dropdown-toggle" id="navbarDropdownNews" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="<%= publications_path %>">PUBLICAÇÕES</a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownNews">
                <a class="dropdown-item" href="<%= publications_path %>">NOTÍCIAS</a>
                <a class="dropdown-item" href="<%= compromisso_e_atitude_path %>">COMPROMISSO E ATITUDE</a>
                <a class="dropdown-item" href="<%= ministerio_publico_path %>">MINISTÉRIO PÚBLICO</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="<%= institutes_path %>">REDES DE ATENDIMENTO</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link js-scroll-trigger dropdown-toggle" id="navbarDropdownArchives" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="<%= archives_path %>">LINKS ÚTEIS</a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownArchives">
                <a class="dropdown-item" href="<%= archives_path %>">TODOS OS ARQUIVOS</a>
                <a class="dropdown-item" href="<%= vagas_path %>">VAGAS DE EMPREGO</a>
                <a class="dropdown-item" href="<%= videos_path %>">VÍDEOS</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link js-scroll-trigger dropdown-toggle" id="navbarDropdownAbout" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="<%= about_path %>">SOBRE O PROJETO</a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownAbout">
                <a class="dropdown-item" href="<%= about_path %>">SOBRE O WEBSITE</a>
                <a class="dropdown-item" href="<%= game_path %>">SOBRE O GAME</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

		<div class="container" style="margin-top: 2%">
			<div class="row">
				<div class="col-lg-8">
					<h1 class="mt-4">
						Publicações
					</h1>
					<hr>

					<% @publications.each do |publication| %>

						<div class="card mb-4">
							<div class="card-body">
								<h2 class="card-title">
									<%= publication.title %>										
								</h2>
								<p class="card-text">
									<%= publication.content.truncate(333).html_safe %>
								</p>
								<a href="<%= publications_path(:publication.id) %>" class="btn btn-primary btn-xl js-scroll-trigger">
									Leia Mais &rarr;
								</a>
							</div>
							<div class="card-footer text-muted">
								Publicado em <%= publication.date %> por Projeto Maria da Penha Chapecó
							</div>
						</div>

					<% end %>

				</div>		
			</div>
		</div>

		<ul class="pagination justify-content-center">
			<%= paginate @publications, :theme => 'twitter-bootstrap-3',
               :pagination_class => "pagination-sm" %>
		</ul>

	   <footer class="py-5 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">
            Projeto Maria da Penha Chapecó | Desenvolvido por <a href="https://instagram.com/ifboniatti" target="_blank">Igor Felipe Boniatti</a>. &copy; Todos os direitos reservados. 2018.
          </p>
        </div>
      </footer>

  </body>

  <script>
      window.fbMessengerPlugins = window.fbMessengerPlugins || {
          init: function () {
              FB.init({
                appId            : '1678638095724206',
                autoLogAppEvents : true,
                xfbml            : true,
                version          : 'v3.0'
              });
          }, callable: []
      };
      window.fbAsyncInit = window.fbAsyncInit || function () {
          window.fbMessengerPlugins.callable.forEach(function (item) { item(); });
          window.fbMessengerPlugins.init();
      };
      setTimeout(function () {
          (function (d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) { return; }
              js = d.createElement(s);
              js.id = id;
              js.src = "//connect.facebook.net/pt_BR/sdk/xfbml.customerchat.js";
              fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));
      }, 0);
  </script>

  <div
      class="fb-customerchat"
      page_id="673776146339397"
      ref="">
  </div>

  <!-- Bootstrap core JavaScript -->
  <%= javascript_include_tag 'jquery/jquery.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap/bootstrap.bundle.min', media: 'all', 'data-turbolinks-track' => true %>

</html>

app/views/publications/new.html.erb
<h1>New Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<!DOCTYPE html>
<html lang="pt-BR">

	<head>
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	    <meta name="author" content="Igor Felipe Boniatti">
	    <meta name="description" content="Protótipo de website para auxiliar vítimas de violência doméstica e familiar no município de Chapecó.">

	    
	    <%= content_for :title, "Publicações - Projeto Maria da Penha Chapecó" %>		
    	<%= favicon_link_tag 'logo_fundo_preto.png' %>

	    <%= stylesheet_link_tag 'bootstrap/bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
	    <%= stylesheet_link_tag 'home/index', media: 'all', 'data-turbolinks-track' => true %>
	</head>

	<body>
	    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
	      <div class="container">
	        <a class="navbar-brand" href="<%= home_path %>">
	          <%= link_to(image_tag("logo_fundo_preto.png", :alt => "logo", :title => "Home"), home_path ) %>
	        </a>
	        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
	          <span class="navbar-toggler-icon"></span>
	        </button>
	        <div class="collapse navbar-collapse" id="navbarResponsive">
	          <ul class="navbar-nav ml-auto">
	            <li class="nav-item">
	              <a class="nav-link js-scroll-trigger" href="http://www.planalto.gov.br/ccivil_03/_Ato2004-2006/2006/Lei/L11340.htm" target="_blank">A LEI MARIA DA PENHA</a>
	            </li>
	            <li class="nav-item">
	              <a class="nav-link js-scroll-trigger" href="<%= doubts_path %>">TIRA-DÚVIDAS</a>
	            </li>
	            <li class="nav-item dropdown active">
	              <a class="nav-link js-scroll-trigger dropdown-toggle" id="navbarDropdownNews" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="<%= publications_path %>">PUBLICAÇÕES</a>
	              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownNews">
	                <a class="dropdown-item" href="<%= publications_path %>">NOTÍCIAS</a>
	                <a class="dropdown-item" href="<%= compromisso_e_atitude_path %>">COMPROMISSO E ATITUDE</a>
	                <a class="dropdown-item" href="<%= ministerio_publico_path %>">MINISTÉRIO PÚBLICO</a>
	              </div>
	            </li>
	            <li class="nav-item">
	              <a class="nav-link js-scroll-trigger" href="<%= institutes_path %>">REDES DE ATENDIMENTO</a>
	            </li>
	            <li class="nav-item dropdown">
	              <a class="nav-link js-scroll-trigger dropdown-toggle" id="navbarDropdownArchives" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="<%= archives_path %>">LINKS ÚTEIS</a>
	              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownArchives">
	                <a class="dropdown-item" href="<%= archives_path %>">TODOS OS ARQUIVOS</a>
	                <a class="dropdown-item" href="<%= vagas_path %>">VAGAS DE EMPREGO</a>
	                <a class="dropdown-item" href="<%= videos_path %>">VÍDEOS</a>
	              </div>
	            </li>
	            <li class="nav-item dropdown">
	              <a class="nav-link js-scroll-trigger dropdown-toggle" id="navbarDropdownAbout" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="<%= about_path %>">SOBRE O PROJETO</a>
	              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownAbout">
	                <a class="dropdown-item" href="<%= about_path %>">SOBRE O WEBSITE</a>
	                <a class="dropdown-item" href="<%= game_path %>">SOBRE O GAME</a>
	              </div>
	            </li>
	          </ul>
	        </div>
	      </div>
	    </nav>

	    <div class="container" style="margin-top: 2%">
			<div class="row">
				<div class="col-lg-8">
					<h1 class="mt-4">
						<%= @publication.title %>						
					</h1>
					<hr>
					<h8>
						Autor: Projeto Maria da Penha | Data de publicação: <%= @publication.date %>							
					</h8>
					<hr>

					<%= @publication.content.html_safe %>

					<p id="notice"><%= notice %></p>

					<div class="card my-4">
						<h5 class="card-header">Deixe um comentário:</h5>
						<div class="card-body">
							<%= form_with model: Comentary.new, url: comentaries_url , method: :post do |form| %>	

								<div class="form-group">
									<%= form.text_area :content, class: 'form-control', rows: 4 %>
								</div>

								<%= form.hidden_field(:publication_id, value: @publication.id) %>

								<!-- <%= form.hidden_field(:date) %> -->

								<%= form.submit class: 'btn btn-primary btn-xl js-scroll-trigger' %>
							<% end %>
						</div>
					</div>

					<!-- COMENTÁRIOS -->
					<% if @publication.comentaries != nil then %> 
						<% @publication.comentaries.each do |comentary| %>
							<div class="media mb-4">
								<img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
								<div class="media-body">
									<label class="form-control card-header">Comentado em: <%= comentary.created_at %></label>
									<label class="form-control card-body"><%= comentary.content %></label>					
								</div>
							</div>
						<% end %>
					<% end %>
				</div>
			</div>
	    </div>

  		<footer class="py-5 bg-dark">
	      <div class="container">
	        <p class="m-0 text-center text-white">
	          Projeto Maria da Penha Chapecó | Desenvolvido por <a href="https://instagram.com/ifboniatti" target="_blank">Igor Felipe Boniatti</a>. &copy; Todos os direitos reservados. 2018.
	        </p>
	      </div>
	    </footer>

  </body>

	<script>
  		window.fbMessengerPlugins = window.fbMessengerPlugins || {
    			init: function () {
      				FB.init({
        				appId            : '1678638095724206',
        				autoLogAppEvents : true,
        				xfbml            : true,
        				version          : 'v3.0'
      				});
    			}, callable: []
  		};
  		window.fbAsyncInit = window.fbAsyncInit || function () {
    			window.fbMessengerPlugins.callable.forEach(function (item) { item(); });
    			window.fbMessengerPlugins.init();
  		};
  		setTimeout(function () {
    			(function (d, s, id) {
      				var js, fjs = d.getElementsByTagName(s)[0];
      				if (d.getElementById(id)) { return; }
      				js = d.createElement(s);
      				js.id = id;
      				js.src = "//connect.facebook.net/pt_BR/sdk/xfbml.customerchat.js";
      				fjs.parentNode.insertBefore(js, fjs);
    			}(document, 'script', 'facebook-jssdk'));
  		}, 0);
	</script>

	<div
  		class="fb-customerchat"
  		page_id="673776146339397"
  		ref="">
	</div>

    <%= javascript_include_tag 'jquery/jquery.min', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'bootstrap/bootstrap.bundle.min', media: 'all', 'data-turbolinks-track' => true %>
  	
</html>