config/routes.rb
Rails.application.routes.draw do
  resources :archives
  devise_for :users
  resources :publications
  resources :doubts
  resources :institutes
  resources :comentaries
  resources :questions

  root :to => "website#home"
  get "home" => "website#home", as: :home  
  get "about" => "website#about", as: :about
  get "game" => "website#game", as: :game
  get "vagas" => "website#vagas", as: :vagas
  get "videos" => "website#videos", as: :videos
  get "compromisso_e_atitude" => "website#compromisso_e_atitude", as: :compromisso_e_atitude
  get "ministerio_publico" => "website#ministerio_publico", as: :ministerio_publico


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
	    
	    if user
	    	if user.access_level.level == 1 # 4: Perfil nível Administrador
	    		can :manage, :all
	    	elsif user.access_level.level == 2 # 2: Perfil nível Editor
	    		can :dashboard
	    		can :access, :rails_admin	    		
	    		can :manage, Archive
	    		can :manage, Doubt
	    		can :manage, Institute
	    		can :manage, Question			
			elsif user.access_level.level == 3 # 3: Perfil nível Publicador
				can :access, :rails_admin
				can :dashboard
				can :manage, Publication
				can :manage, Comentary
			elsif user.access_level.level == 4 # 4: Perfil nível Policial
				can :access, :rails_admin
				can :dashboard				
				can :manage, OccurrenceBulletin
				can :manage, AnonymousDenounciation
				can :manage, Person
				can :manage, Phone
				can :manage, Address
			end	
	    end

	end
end

app/models/access_level.rb
class AccessLevel < ApplicationRecord
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :category
  has_attached_file :arch
  validates :arch, :attachment_content_type => { :content_type => ['application/pdf', 'video/mp4'] }
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comentary.rb
class Comentary < ApplicationRecord
  belongs_to :publication
end

app/models/doubt.rb
class Doubt < ApplicationRecord
  belongs_to :question
end

app/models/institute.rb
class Institute < ApplicationRecord
  belongs_to :phone
  belongs_to :address
end

app/models/news.rb
class News < ApplicationRecord

end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :phone
  belongs_to :address
end

app/models/phone.rb
class Phone < ApplicationRecord
end

app/models/publication.rb
class Publication < ApplicationRecord
	has_many :comentaries
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
include RailsAdminCharts

class User < ApplicationRecord 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :access_level
  belongs_to :person
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :set_archive, only: [:show, :edit, :update, :destroy]

  # GET /archives
  # GET /archives.json
  def index
    #@archives = Archive.all
    @archives = Archive.page(params[:page]).per(9)
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
  end

  # GET /archives/new
  def new
    @archive = Archive.new
  end

  # GET /archives/1/edit
  def edit
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = Archive.new(archive_params)

    respond_to do |format|
      if @archive.save
        format.html { redirect_to @archive, notice: 'Archive was successfully created.' }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1
  # PATCH/PUT /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to @archive, notice: 'Archive was successfully updated.' }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to archives_url, notice: 'Archive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archive_params
      params.require(:archive).permit(:name, :category_id, :description, :arch)
    end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/doubts_helper.rb
module DoubtsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/archives/_form.html.erb
<%= form_with(model: archive, local: true, html: {multipart: true}) do |form| %>
  <% if archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% archive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :arch %>
    <%= form.file_field :arch %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/archives/edit.html.erb
<h1>Editing Archive</h1>

<%= render 'form', archive: @archive %>

<%= link_to 'Show', @archive %> |
<%= link_to 'Back', archives_path %>

app/views/archives/index.html.erb
<!DOCTYPE html>
<html lang="pt-BR">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Igor Felipe Boniatti">
    <meta name="description" content="Protótipo de website para auxiliar vítimas de violência doméstica e familiar no município de Chapecó.">

    <%= content_for :title, "Links Úteis - Projeto Maria da Penha Chapecó" %>   
    <%= favicon_link_tag 'logo_fundo_preto.png' %>

    <%= stylesheet_link_tag 'bootstrap/bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'home/index', media: 'all', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="<%= home_path %>">
          <%= link_to(image_tag("logo_fundo_preto.png", :alt => "logo", :title => "Home"), home_path ) %>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="http://www.planalto.gov.br/ccivil_03/_Ato2004-2006/2006/Lei/L11340.htm" target="_blank">A LEI MARIA DA PENHA</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="<%= doubts_path %>">TIRA-DÚVIDAS</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link js-scroll-trigger dropdown-toggle" id="navbarDropdownNews" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="<%= publications_path %>">PUBLICAÇÕES</a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownNews">
                <a class="dropdown-item" href="<%= publications_path %>">NOTÍCIAS</a>
                <a class="dropdown-item" href="<%= compromisso_e_atitude_path %>">COMPROMISSO E ATITUDE</a>
                <a class="dropdown-item" href="<%= ministerio_publico_path %>">MINISTÉRIO PÚBLICO</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="<%= institutes_path %>">REDES DE ATENDIMENTO</a>
            </li>
            <li class="nav-item dropdown active">
              <a class="nav-link js-scroll-trigger dropdown-toggle" id="navbarDropdownArchives" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="<%= archives_path %>">LINKS ÚTEIS</a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownArchives">
                <a class="dropdown-item" href="<%= archives_path %>">TODOS OS ARQUIVOS</a>
                <a class="dropdown-item" href="<%= vagas_path %>">VAGAS DE EMPREGO</a>
                <a class="dropdown-item" href="<%= videos_path %>">VÍDEOS</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link js-scroll-trigger dropdown-toggle" id="navbarDropdownAbout" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="<%= about_path %>">SOBRE O PROJETO</a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownAbout">
                <a class="dropdown-item" href="<%= about_path %>">SOBRE O WEBSITE</a>
                <a class="dropdown-item" href="<%= game_path %>">SOBRE O GAME</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="jumbotron my-2">
      <h1 class="display-4 text-center">LINKS ÚTEIS</h1>
    </header><p>

    <div class="container">
      
      <div class="row">

        <% @archives.each do |archive| %>

          <div class="col-lg-4 mb-4">
            <div class="card h-100">
              <h4 class="card-header"><%= archive.name %></h4>
              <div class="card-body">
                <p class="card-body"><%= archive.category.name %></p>
                <p class="card-text"><%= archive.description %></p>
              </div>
              <div class="card-footer">
                <a href="<%= archive.arch.url %>" target="_blank" class="btn btn-primary">Download</a>
              </div>
            </div>
          </div>

        <% end %>

      </div>
    </div>

    <ul class="pagination justify-content-center">
      <%= paginate @archives, :theme => 'twitter-bootstrap-3',
               :pagination_class => "pagination-sm" %>
    </ul>
    
    <footer class="py-5 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">
            Projeto Maria da Penha Chapecó | Desenvolvido por <a href="https://instagram.com/ifboniatti" target="_blank">Igor Felipe Boniatti</a>. &copy; Todos os direitos reservados. 2018.
          </p>
        </div>
      </footer>

    </body>

  <script>
      window.fbMessengerPlugins = window.fbMessengerPlugins || {
          init: function () {
              FB.init({
                appId            : '1678638095724206',
                autoLogAppEvents : true,
                xfbml            : true,
                version          : 'v3.0'
              });
          }, callable: []
      };
      window.fbAsyncInit = window.fbAsyncInit || function () {
          window.fbMessengerPlugins.callable.forEach(function (item) { item(); });
          window.fbMessengerPlugins.init();
      };
      setTimeout(function () {
          (function (d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) { return; }
              js = d.createElement(s);
              js.id = id;
              js.src = "//connect.facebook.net/pt_BR/sdk/xfbml.customerchat.js";
              fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));
      }, 0);
  </script>

  <%= javascript_include_tag 'jquery/jquery.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap/bootstrap.bundle.min', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'home/index.min', media: 'all', 'data-turbolinks-track' => true %>

</html>

app/views/archives/new.html.erb
<h1>New Archive</h1>

<%= render 'form', archive: @archive %>

<%= link_to 'Back', archives_path %>

app/views/archives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @archive.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @archive.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @archive.description %>
</p>

<p>
  <strong>Arch:</strong>
  <%= @archive.arch %>
</p>

<%= link_to 'Edit', edit_archive_path(@archive) %> |
<%= link_to 'Back', archives_path %>